import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'
import { signIn } from 'next-auth/react'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();

  const goToOnboardingPage = () => {
    router.push('/onboard');
  };

  const handleSignIn = async () => {
    const result = await signIn('github', { callbackUrl: './myavatar' });
    if (result?.error) {
    } else if (result?.url) {
      router.push(result.url);
    }
  };

  return (
    <>
      <Head>
        <title>Web Avatar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className='container'>
          <h1 className='title'>Web-Avatar</h1>
          <h2>The pixels yor browsing experience was missing</h2>
          <h4>Are you coming back?</h4>
          <h5>Go to your session</h5>
          <h1><button className='action-button' onClick={handleSignIn}>Sign In</button></h1>
          <h4>Are you new to the site?</h4>
          <h5>Find out what its all about</h5>
          <h1><button className='action-button' onClick={goToOnboardingPage}>Go to Onboarding</button></h1>
        </div>
      </main >
    </>
  )
}




