import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(() => {
    if (document) {
      const navAvatar = document.getElementById("navAvatar");
      let currentKeys = [];

      const UP = 'w';
      const LEFT = 'a';
      const DOWN = 's';
      const RIGHT = 'd';

      //document.querySelectorAll

      const allDetectableBlocks = document.querySelectorAll(".detectable");
      console.log(allDetectableBlocks);

      function isColliding(block1, block2) {
        return !(
          block1.bottom < block2.top ||
          block1.top > block2.bottom ||
          block1.right < block2.left ||
          block1.left > block2.right
        );
      }

      function detectCollision() {
        let me = navAvatar.getBoundingClientRect();

        allDetectableBlocks.forEach((currentBlock) => {
          let block = currentBlock.getBoundingClientRect();

          if (isColliding(me, block)) {
            currentBlock.style.background = 'green';
            navAvatar.style.background = 'green'
            console.log(navAvatar.style.background);
          }
          else {
            currentBlock.style.background = 'red'
            navAvatar.style.background = 'black'
          }
        })
      }

      function moveLoop() {
        let leftPos = parseInt(navAvatar.style.left);
        let topPos = parseInt(navAvatar.style.top);

        if (currentKeys[LEFT]) navAvatar.style.left = leftPos - 3 + 'px';
        if (currentKeys[RIGHT]) navAvatar.style.left = leftPos + 3 + 'px';
        if (currentKeys[UP]) navAvatar.style.top = topPos - 3 + 'px';
        if (currentKeys[DOWN]) navAvatar.style.top = topPos + 3 + 'px';

        detectCollision();

        window.requestAnimationFrame(moveLoop);
      }
      window.requestAnimationFrame(moveLoop);

      document.body.addEventListener("keydown", (infoAboutKey) => { currentKeys[infoAboutKey.key] = true; /* console.log(currentKeys)  */ })
      document.body.addEventListener("keyup", (infoAboutKey) => { currentKeys[infoAboutKey.key] = false })
      window.addEventListener("DOMContentLoaded", () => { moveLoop() });
    }
  }, [])

  return (
    <>
      <Head>
        <title>Web Avatar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <p>Use wasd to move up, left, down or right</p>
          <div id='navAvatar' className={styles.navAvatar} style={{ top: '200px', left: '500px' }}>nav</div>
          <div id='block1' className={`detectable ${styles.testBlock}`} style={{ top: '100px', left: '1000px', background: 'red' }}>block1</div>
          <div id='block2' className={`detectable ${styles.testBlock}`} style={{ top: '400px', left: '700px', background: 'red' }}>block2</div>
          <div id='block3' className={`detectable ${styles.testBlock}`} style={{ top: '600px', left: '300px', background: 'red' }}>block3</div>
        </div>
        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main >
    </>
  )
}




