import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(() => {
    if (document) {
      const navAvatar = document.getElementById("navAvatar");
      let isAvatarMoving = false;
      let isAvatarInteracting = false;

      let currentKeys = [];
      const UP = 'w';
      const LEFT = 'a';
      const DOWN = 's';
      const RIGHT = 'd';
      const ACTION = 'e';
      const BACK = 'q';

      let canMove = true;
      const allDetectableBlocks = document.querySelectorAll(".detectable");

      function isColliding(block1, block2) {
        return !(
          block1.bottom < block2.top ||
          block1.top > block2.bottom ||
          block1.right < block2.left ||
          block1.left > block2.right
        );
      }


      function detectCollision() {
        let me = navAvatar.getBoundingClientRect();
        let blockCollisions = {};

        Array.prototype.forEach.call(allDetectableBlocks, (currentBlock) => {
          var collidingWithThisBlock = false;
          let block = currentBlock.getBoundingClientRect();

          if (isColliding(me, block)) {

            currentBlock.style.background = 'green';
          }
          else {
            currentBlock.style.background = 'red'
          }
        })
      }

      function detectPlayerCollision() {
        let me = navAvatar.getBoundingClientRect();

        if (Array.from(allDetectableBlocks).some(currentBlock => {
          let block = currentBlock.getBoundingClientRect();
          return isColliding(me, block)
        })) {
          isAvatarInteracting = true;
          navAvatar.style.background = 'green';
        }
        else {
          isAvatarInteracting = false;
          navAvatar.style.background = 'black';
        }
      }

      function moveLoop() {
        let leftPos = parseInt(navAvatar.style.left);
        let topPos = parseInt(navAvatar.style.top);
        let menuLeftPos = parseInt(navAvatar.style.left);
        let menuTopPos = parseInt(navAvatar.style.top);

        if (currentKeys[LEFT] && canMove) navAvatar.style.left = leftPos - 3 + 'px';
        if (currentKeys[RIGHT] && canMove) navAvatar.style.left = leftPos + 3 + 'px';
        if (currentKeys[UP] && canMove) navAvatar.style.top = topPos - 3 + 'px';
        if (currentKeys[DOWN] && canMove) navAvatar.style.top = topPos + 3 + 'px';

        if (currentKeys[ACTION] && isAvatarInteracting) {
          document.getElementById('menu').style.left = menuLeftPos + 50 + 'px';
          document.getElementById('menu').style.top = menuTopPos - 50 + 'px';
          canMove = false;
          document.getElementById('menu').style.display = 'block';
        }
        if (currentKeys[BACK] && isAvatarInteracting) {
          canMove = true;
          document.getElementById('menu').style.display = 'none';
        }

        detectCollision();
        detectPlayerCollision();

        window.requestAnimationFrame(moveLoop);
      }
      window.requestAnimationFrame(moveLoop);

      document.body.addEventListener("keydown", (infoAboutKey) => { currentKeys[infoAboutKey.key] = true; /* console.log(currentKeys)  */ })
      document.body.addEventListener("keyup", (infoAboutKey) => { currentKeys[infoAboutKey.key] = false; })
      window.addEventListener("DOMContentLoaded", () => { moveLoop() });
    }
  }, [])

  return (
    <>
      <Head>
        <title>Web Avatar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <p>Use wasd to move up, left, down or right</p>
          <div id='menu' className={styles.menu} style={{ display: 'none', top: '250px', left: '550px' }}>e: continue / q: back</div>
          <div id='navAvatar' className={styles.navAvatar} style={{ top: '200px', left: '500px', background: 'black' }}>nav</div>
          <div id='block1' className={`detectable ${styles.testBlock}`} style={{ top: '600px', left: '70px', background: 'red' }}>block1</div>
          <div id='block2' className={`detectable ${styles.testBlock}`} style={{ top: '600px', left: '200px', background: 'red' }}>block2</div>
          <div id='block3' className={`detectable ${styles.testBlock}`} style={{ top: '600px', left: '400px', background: 'red' }}>block3</div>
          <button type='button' onClick={() => { console.log("button pressed") }}>Click Me</button>
        </div>
      </main >
    </>
  )
}

{/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}




